# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import chat_pb2 as protos_dot_chat__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """The main service definition for the chat application.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignUp = channel.unary_unary(
                '/ChatService/SignUp',
                request_serializer=protos_dot_chat__pb2.SignUpRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/ChatService/Login',
                request_serializer=protos_dot_chat__pb2.LoginRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/ChatService/Logout',
                request_serializer=protos_dot_chat__pb2.LogoutRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetUsers = channel.unary_unary(
                '/ChatService/GetUsers',
                request_serializer=protos_dot_chat__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.UserList.FromString,
                _registered_method=True)
        self.PostMessage = channel.unary_unary(
                '/ChatService/PostMessage',
                request_serializer=protos_dot_chat__pb2.PostMessageRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StreamMessages = channel.unary_stream(
                '/ChatService/StreamMessages',
                request_serializer=protos_dot_chat__pb2.StreamRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.ChatMessage.FromString,
                _registered_method=True)
        self.GetChatHistory = channel.unary_unary(
                '/ChatService/GetChatHistory',
                request_serializer=protos_dot_chat__pb2.ChatHistoryRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.ChatHistoryResponse.FromString,
                _registered_method=True)
        self.GetMyGroups = channel.unary_unary(
                '/ChatService/GetMyGroups',
                request_serializer=protos_dot_chat__pb2.GetMyGroupsRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.GroupList.FromString,
                _registered_method=True)
        self.CreateGroup = channel.unary_unary(
                '/ChatService/CreateGroup',
                request_serializer=protos_dot_chat__pb2.CreateGroupRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.AddUserToGroup = channel.unary_unary(
                '/ChatService/AddUserToGroup',
                request_serializer=protos_dot_chat__pb2.ManageGroupRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RemoveUserFromGroup = channel.unary_unary(
                '/ChatService/RemoveUserFromGroup',
                request_serializer=protos_dot_chat__pb2.ManageGroupRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetAllGroups = channel.unary_unary(
                '/ChatService/GetAllGroups',
                request_serializer=protos_dot_chat__pb2.GetAllGroupsRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.GroupList.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """The main service definition for the chat application.
    """

    def SignUp(self, request, context):
        """--- User Authentication ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsers(self, request, context):
        """--- Core Chat Functionality ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyGroups(self, request, context):
        """--- User Group Management ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroup(self, request, context):
        """--- Administrator Functions ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUserToGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUserFromGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignUp': grpc.unary_unary_rpc_method_handler(
                    servicer.SignUp,
                    request_deserializer=protos_dot_chat__pb2.SignUpRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.StatusResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=protos_dot_chat__pb2.LoginRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=protos_dot_chat__pb2.LogoutRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.StatusResponse.SerializeToString,
            ),
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=protos_dot_chat__pb2.GetUsersRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.UserList.SerializeToString,
            ),
            'PostMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PostMessage,
                    request_deserializer=protos_dot_chat__pb2.PostMessageRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.StatusResponse.SerializeToString,
            ),
            'StreamMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMessages,
                    request_deserializer=protos_dot_chat__pb2.StreamRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.ChatMessage.SerializeToString,
            ),
            'GetChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatHistory,
                    request_deserializer=protos_dot_chat__pb2.ChatHistoryRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.ChatHistoryResponse.SerializeToString,
            ),
            'GetMyGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyGroups,
                    request_deserializer=protos_dot_chat__pb2.GetMyGroupsRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.GroupList.SerializeToString,
            ),
            'CreateGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroup,
                    request_deserializer=protos_dot_chat__pb2.CreateGroupRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.StatusResponse.SerializeToString,
            ),
            'AddUserToGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUserToGroup,
                    request_deserializer=protos_dot_chat__pb2.ManageGroupRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.StatusResponse.SerializeToString,
            ),
            'RemoveUserFromGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUserFromGroup,
                    request_deserializer=protos_dot_chat__pb2.ManageGroupRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.StatusResponse.SerializeToString,
            ),
            'GetAllGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllGroups,
                    request_deserializer=protos_dot_chat__pb2.GetAllGroupsRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.GroupList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """The main service definition for the chat application.
    """

    @staticmethod
    def SignUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatService/SignUp',
            protos_dot_chat__pb2.SignUpRequest.SerializeToString,
            protos_dot_chat__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatService/Login',
            protos_dot_chat__pb2.LoginRequest.SerializeToString,
            protos_dot_chat__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatService/Logout',
            protos_dot_chat__pb2.LogoutRequest.SerializeToString,
            protos_dot_chat__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatService/GetUsers',
            protos_dot_chat__pb2.GetUsersRequest.SerializeToString,
            protos_dot_chat__pb2.UserList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatService/PostMessage',
            protos_dot_chat__pb2.PostMessageRequest.SerializeToString,
            protos_dot_chat__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ChatService/StreamMessages',
            protos_dot_chat__pb2.StreamRequest.SerializeToString,
            protos_dot_chat__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatService/GetChatHistory',
            protos_dot_chat__pb2.ChatHistoryRequest.SerializeToString,
            protos_dot_chat__pb2.ChatHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMyGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatService/GetMyGroups',
            protos_dot_chat__pb2.GetMyGroupsRequest.SerializeToString,
            protos_dot_chat__pb2.GroupList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatService/CreateGroup',
            protos_dot_chat__pb2.CreateGroupRequest.SerializeToString,
            protos_dot_chat__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddUserToGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatService/AddUserToGroup',
            protos_dot_chat__pb2.ManageGroupRequest.SerializeToString,
            protos_dot_chat__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveUserFromGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatService/RemoveUserFromGroup',
            protos_dot_chat__pb2.ManageGroupRequest.SerializeToString,
            protos_dot_chat__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatService/GetAllGroups',
            protos_dot_chat__pb2.GetAllGroupsRequest.SerializeToString,
            protos_dot_chat__pb2.GroupList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
