# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/llm_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/llm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/llm_service.proto\"B\n\x1dGetChatRecommendationsRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x12\n\nchannel_id\x18\x02 \x01(\t\"9\n\x1eGetChatRecommendationsResponse\x12\x17\n\x0frecommendations\x18\x01 \x03(\t2g\n\nLLMService\x12Y\n\x16GetChatRecommendations\x12\x1e.GetChatRecommendationsRequest\x1a\x1f.GetChatRecommendationsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCHATRECOMMENDATIONSREQUEST']._serialized_start=28
  _globals['_GETCHATRECOMMENDATIONSREQUEST']._serialized_end=94
  _globals['_GETCHATRECOMMENDATIONSRESPONSE']._serialized_start=96
  _globals['_GETCHATRECOMMENDATIONSRESPONSE']._serialized_end=153
  _globals['_LLMSERVICE']._serialized_start=155
  _globals['_LLMSERVICE']._serialized_end=258
# @@protoc_insertion_point(module_scope)
